### ISSUE TITLE
minor typo in ReadME

### ISSUE THREAD

**Issue by seongsukim-ml** [GLAD-RUC/FastEGNN#1]
Hello, thank you for your great work!

I found a minor typo in install pip:

`pip -r install requirements.txt`

to

`pip install -r requirements.txt`

**Comment by dhcpack** [comment]
Hello @seongsukim-ml,

Thank you for pointing out the typo in the ReadME and for your kind words and I have corrected the typo.

Your feedback is greatly appreciated. If you notice any other issues or have further suggestions, please feel free to let us know.

Best regards!
